[2023-06-14T21:53:28.691+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2023-06-14T21:38:08.435514+00:00 [queued]>
[2023-06-14T21:53:28.698+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2023-06-14T21:38:08.435514+00:00 [queued]>
[2023-06-14T21:53:28.698+0000] {taskinstance.py:1308} INFO - Starting attempt 4 of 4
[2023-06-14T21:53:28.710+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2023-06-14 21:38:08.435514+00:00
[2023-06-14T21:53:28.719+0000] {standard_task_runner.py:57} INFO - Started process 903 to run task
[2023-06-14T21:53:28.724+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', 'manual__2023-06-14T21:38:08.435514+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpxfineac2']
[2023-06-14T21:53:28.730+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask pyspark_train_classifier_model
[2023-06-14T21:53:28.806+0000] {task_command.py:410} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2023-06-14T21:38:08.435514+00:00 [running]> on host 6426fae5ea9e
[2023-06-14T21:53:28.902+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='agile_data_science_batch_prediction_model_training' AIRFLOW_CTX_TASK_ID='pyspark_train_classifier_model' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T21:38:08.435514+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-14T21:38:08.435514+00:00'
[2023-06-14T21:53:28.907+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-14T21:53:28.908+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\nspark-submit --master spark://spark-master:7077   //TrainingJob.py   /']
[2023-06-14T21:53:28.921+0000] {subprocess.py:86} INFO - Output:
[2023-06-14T21:53:28.924+0000] {subprocess.py:93} INFO - /bin/bash: line 2: spark-submit: command not found
[2023-06-14T21:53:28.924+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-14T21:53:28.936+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-14T21:53:28.939+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20230614T213808, start_date=20230614T215328, end_date=20230614T215328
[2023-06-14T21:53:28.952+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 28 for task pyspark_train_classifier_model (Bash command failed. The command returned a non-zero exit code 127.; 903)
[2023-06-14T21:53:28.978+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T21:53:29.003+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
